services:
  - type: web
    name: physio-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build && npx prisma generate
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
    healthCheckPath: /

